# Sanity: start the demo from a configuration file and verify the configured values are active;
# an invalid configuration must be refused with a non-zero exit before the lifecycle runs.
execute_process(COMMAND ${DEMO_EXE} ${DEMO_CONFIG} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
message("${out}")
if(NOT rc EQUAL 0)
    message(FATAL_ERROR "kritva_demo with config exited with ${rc}: ${err}")
endif()
string(FIND "${out}" "config: runtime.name=kritva_demo runtime.tick_ms=100 parameters=2" idx)
if(idx LESS 0)
    message(FATAL_ERROR "sanity: configured values are not active in demo output")
endif()
string(FIND "${out}" "state=RUNNING" idx)
if(idx LESS 0)
    message(FATAL_ERROR "sanity: demo did not reach RUNNING with the configuration")
endif()

set(bad "${CMAKE_CURRENT_BINARY_DIR}/kritva_demo_invalid.conf")
file(WRITE "${bad}" "runtime.name=demo\nruntime.tick_ms=0\n")
execute_process(COMMAND ${DEMO_EXE} "${bad}" RESULT_VARIABLE rc OUTPUT_VARIABLE out)
message("${out}")
if(rc EQUAL 0)
    message(FATAL_ERROR "sanity: invalid configuration was accepted")
endif()
string(FIND "${out}" "state=READY" idx)
if(NOT idx LESS 0)
    message(FATAL_ERROR "sanity: lifecycle ran despite invalid configuration")
endif()
