# =============================================================================
# Copyright (c) 2026 KritvaOS
# SPDX-License-Identifier: Apache-2.0
#
# File        : Dockerfile
# Description : <short description>
#
# Component   : <component>
# Module      : <module>
# Layer       : Infrastructure
#
# Requirements: <requirement IDs>       # Optional
#
# Author      : <team/name>
# Created     : DD-MM-YYYY
# =============================================================================
